### ISSUE TITLE
Start of speech seem to be cut off on every single sentence.

### ISSUE THREAD

**Issue by heinrichferreira** [C-Nedelcu/talk-to-chatgpt#92] opened 2023-04-30 22:15 UTC
Love your extension.  There is only one annoying issue and I do not know if I am the only one experiencing it.  When any of the voices start speaking any sentence, it seems like the audio device is being activated too late because the first few milliseconds of the speech is being cut off.  After a while this becomes very distracting.  I would love it if you could fix this.  Incidentally it only happens in Chrome Extension not in Edge.

**Comment by C-Nedelcu** [comment] 2023-05-01 02:40
Hello heinrich,
I am going to assume you use a bluetooth speaker of headset.
This is quite a common issue, and, you guessed it, it's not caused by the extension but by the browser.
Keep in mind all my extension does is use common web browser APIs
You could probably try this maybe:
https://github.com/gurux13/chrome-audio-delay/
Or, play some music at low volume so that your bluetooth device is already synchronized, and then you will notice your cutoff no longer happens because your bluetooth device is already active.
I have to close this issue because it is not related to my extension - there isn't anything I can do to fix it.

**Closed by C-Nedelcu** 2023-05-01 02:40 UTC

**Comment by heinrichferreira** [comment] 2023-05-01 04:00
No worries.  The fact that it works perfectly on Edge kind of shows that it is a browser specific issue.  I was starting to switch to Edge anyway due to the ChatGPT4 availability in it
